In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('carprices.csv')

In [3]:
df

Car_Model  Mileage  Sell_Price  Age
0           BMW X5    69000       18000    6
1           BMW X5    35000       34000    3
2           BMW X5    57000       26100    5
3           BMW X5    22500       40000    2
4           BMW X5    46000       31500    4
5             Audi    59000       29400    5
6             Audi    52000       32000    5
7             Audi    72000       19300    6
8             Audi    91000       12000    8
9   Mercedez Benz     67000       22000    6
10  Mercedez Benz     83000       20000    7
11  Mercedez Benz     79000       21000    7
12  Mercedez Benz     59000       33000    5
13          Toyota    51000       42000    4
14          Toyota    65000       32000    7
15          Toyota    39000       55000    5

In [4]:
df.dtypes

Car_Model     object
Mileage        int64
Sell_Price     int64
Age            int64
dtype: object

In [6]:
df['Car_Model'].unique()

array(['BMW X5', 'Audi', 'Mercedez Benz ', 'Toyota'], dtype=object)

In [7]:
ohe = OneHotEncoder()

In [8]:
ohe

OneHotEncoder()

In [10]:
ohe.fit_transform(df[['Car_Model']]).toarray()

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [11]:
f_array=ohe.fit_transform(df[['Car_Model']]).toarray()

In [13]:
f_array

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [14]:
ohe.categories_

[array(['Audi', 'BMW X5', 'Mercedez Benz ', 'Toyota'], dtype=object)]

In [15]:
f_labels=ohe.categories_

In [16]:
f_labels

[array(['Audi', 'BMW X5', 'Mercedez Benz ', 'Toyota'], dtype=object)]

In [17]:
np.array(f_labels).ravel()

array(['Audi', 'BMW X5', 'Mercedez Benz ', 'Toyota'], dtype=object)

In [18]:
f_labels= np.array(f_labels).ravel()

In [19]:
f_labels

array(['Audi', 'BMW X5', 'Mercedez Benz ', 'Toyota'], dtype=object)

In [20]:
pd.DataFrame(f_array, columns = f_labels)

Audi  BMW X5  Mercedez Benz   Toyota
0    0.0     1.0             0.0     0.0
1    0.0     1.0             0.0     0.0
2    0.0     1.0             0.0     0.0
3    0.0     1.0             0.0     0.0
4    0.0     1.0             0.0     0.0
5    1.0     0.0             0.0     0.0
6    1.0     0.0             0.0     0.0
7    1.0     0.0             0.0     0.0
8    1.0     0.0             0.0     0.0
9    0.0     0.0             1.0     0.0
10   0.0     0.0             1.0     0.0
11   0.0     0.0             1.0     0.0
12   0.0     0.0             1.0     0.0
13   0.0     0.0             0.0     1.0
14   0.0     0.0             0.0     1.0
15   0.0     0.0             0.0     1.0

In [21]:
features = pd.DataFrame(f_array, columns = f_labels)

In [22]:
features

Audi  BMW X5  Mercedez Benz   Toyota
0    0.0     1.0             0.0     0.0
1    0.0     1.0             0.0     0.0
2    0.0     1.0             0.0     0.0
3    0.0     1.0             0.0     0.0
4    0.0     1.0             0.0     0.0
5    1.0     0.0             0.0     0.0
6    1.0     0.0             0.0     0.0
7    1.0     0.0             0.0     0.0
8    1.0     0.0             0.0     0.0
9    0.0     0.0             1.0     0.0
10   0.0     0.0             1.0     0.0
11   0.0     0.0             1.0     0.0
12   0.0     0.0             1.0     0.0
13   0.0     0.0             0.0     1.0
14   0.0     0.0             0.0     1.0
15   0.0     0.0             0.0     1.0

In [23]:
pd.concat([df,features], axis=1)

Car_Model  Mileage  Sell_Price  Age  Audi  BMW X5  Mercedez Benz   \
0           BMW X5    69000       18000    6   0.0     1.0             0.0   
1           BMW X5    35000       34000    3   0.0     1.0             0.0   
2           BMW X5    57000       26100    5   0.0     1.0             0.0   
3           BMW X5    22500       40000    2   0.0     1.0             0.0   
4           BMW X5    46000       31500    4   0.0     1.0             0.0   
5             Audi    59000       29400    5   1.0     0.0             0.0   
6             Audi    52000       32000    5   1.0     0.0             0.0   
7             Audi    72000       19300    6   1.0     0.0             0.0   
8             Audi    91000       12000    8   1.0     0.0             0.0   
9   Mercedez Benz     67000       22000    6   0.0     0.0             1.0   
10  Mercedez Benz     83000       20000    7   0.0     0.0             1.0   
11  Mercedez Benz     79000       21000    7   0.0     0.0             1.0   
12  Mercedez Benz     59000       33000    5   0.0     0.0             1.0   
13          Toyota    51000       42000    4   0.0     0.0             0.0   
14          Toyota    65000       32000    7   0.0     0.0             0.0   
15          Toyota    39000       55000    5   0.0     0.0             0.0   

    Toyota  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
5      0.0  
6      0.0  
7      0.0  
8      0.0  
9      0.0  
10     0.0  
11     0.0  
12     0.0  
13     1.0  
14     1.0  
15     1.0

In [24]:
n_df=pd.concat([df,features],axis=1)

In [25]:
n_df.head()

Car_Model  Mileage  Sell_Price  Age  Audi  BMW X5  Mercedez Benz   Toyota
0    BMW X5    69000       18000    6   0.0     1.0             0.0     0.0
1    BMW X5    35000       34000    3   0.0     1.0             0.0     0.0
2    BMW X5    57000       26100    5   0.0     1.0             0.0     0.0
3    BMW X5    22500       40000    2   0.0     1.0             0.0     0.0
4    BMW X5    46000       31500    4   0.0     1.0             0.0     0.0

In [33]:
ndf = n_df.drop(['Car_Model'], axis=1)

In [34]:
ndf.head()

Mileage  Sell_Price  Age  Audi  BMW X5  Mercedez Benz   Toyota
0    69000       18000    6   0.0     1.0             0.0     0.0
1    35000       34000    3   0.0     1.0             0.0     0.0
2    57000       26100    5   0.0     1.0             0.0     0.0
3    22500       40000    2   0.0     1.0             0.0     0.0
4    46000       31500    4   0.0     1.0             0.0     0.0

In [ ]:
# Price predection for Car Model=Audi Mileage=45000 Age=8

In [40]:
y=ndf.pop('Sell_Price')
x=ndf

In [41]:
x

Mileage  Age  Audi  BMW X5  Mercedez Benz   Toyota
0     69000    6   0.0     1.0             0.0     0.0
1     35000    3   0.0     1.0             0.0     0.0
2     57000    5   0.0     1.0             0.0     0.0
3     22500    2   0.0     1.0             0.0     0.0
4     46000    4   0.0     1.0             0.0     0.0
5     59000    5   1.0     0.0             0.0     0.0
6     52000    5   1.0     0.0             0.0     0.0
7     72000    6   1.0     0.0             0.0     0.0
8     91000    8   1.0     0.0             0.0     0.0
9     67000    6   0.0     0.0             1.0     0.0
10    83000    7   0.0     0.0             1.0     0.0
11    79000    7   0.0     0.0             1.0     0.0
12    59000    5   0.0     0.0             1.0     0.0
13    51000    4   0.0     0.0             0.0     1.0
14    65000    7   0.0     0.0             0.0     1.0
15    39000    5   0.0     0.0             0.0     1.0

In [42]:
model = linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [47]:
model.score(x,y)*100

94.61669991799322

In [48]:
model.predict([[45000,8,1,0,0,0]])

array([39677.03033127])